spring:
  application:
    name: ai-learning-hub-backend
  datasource:
    url: jdbc:mariadb://localhost:3306/ai_learning_hub
    username: root
    password: sql1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
app:
  jwt:
    secret: your_jwt_secret_key_here_which_should_be_very_long_and_secure_in_production
    expiration-ms: 86400000 # 24 ????

# OpenAI API Configuration
openai:
  api-key: your_openai_api_key
  model: gpt-4
  endpoint: https://api.openai.com/v1/chat/completions

# Logging
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.ailearninghub: DEBUG